language: rust
dist: xenial
rust: stable
branches:
  only:
    - master
cache: cargo
before_script: make travis-init
script: make travis
deploy:
  - provider: script
    skip_cleanup: true
    script: make travis-deploy
    on:
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key:
      secure:
    on:
      repo: tyrchen/simple_servers
      branch: master
